// Vue/fourth-vue-app/src/App.vue
<template>
    <div class="container">
        <form>
            <div class="row">
                <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
                    <h1>File a Complaint</h1>
                    <hr>
                    <div class="form-group">
                        <label for="email">Mail</label>
                        <input
                                type="text"
                                id="email"
                                class="form-control"
                                v-model="userData.email">
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input
                                type="password"
                                id="password"
                                class="form-control"
                                v-model.lazy="userData.password">

                        <p>{{userData.password}}</p>
                    </div>
                    <div class="form-group">
                        <label for="age">Age</label>
                        <input
                                type="number"
                                id="age"
                                class="form-control"
                                v-model="userData.age">
                    </div>

                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 form-group">
                    <label for="message">Message</label><br>
                    <!-- Interpolation between <textarea>{{ test }}</textarea> doesn't work!-->
                    <textarea
                            id="message"
                            rows="5"
                            class="form-control"
                            v-model="message"></textarea>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
                    <div class="form-group">
                        <label for="sendmail">
                            <input
                                    type="checkbox"
                                    id="sendmail"
                                    value="SendMail"
                                    v-model="sendMail"> Send Mail
                        </label>
                        <label for="sendInfomail">
                            <input
                                    type="checkbox"
                                    id="sendInfomail"
                                    value="SendInfoMail"
                                    v-model="sendMail"> Send Infomail
                        </label>
                    </div>

                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 form-group">
                    <label for="male">
                        <input
                                type="radio"
                                id="male"
                                value="Male"> Male
                    </label>
                    <label for="female">
                        <input
                                type="radio"
                                id="female"
                                value="Female"> Female
                    </label>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 from-group">
                    <label for="priority">Priority</label>
                    <select
                            id="priority"
                            class="form-control">
                        <option></option>
                    </select>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
                    <button
                            class="btn btn-primary">Submit!
                    </button>
                </div>
            </div>
        </form>
        <hr>
        <div class="row">
            <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4>Your Data</h4>
                    </div>
                    <div class="panel-body">
                        <p>Mail: {{userData.email}}</p>
                        <p>Password: {{userData.password}}</p>
                        <p>Age: {{userData.age}}</p>
                        <p style="white-space: pre">Message: {{ message }}</p>
                        <p><strong>Send Mail?</strong></p>
                        <ul>
                            <li v-for="(item, index) in sendMail" v-bind:key="index">{{item}}</li>
                        </ul>
                        <p>Gender:</p>
                        <p>Priority:</p>
                        <p>Switched:</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
    export default {

        data: function(){

            return{

                userData: {
                    username: '',
                    password: '',
                    email: '',
                    age: 30
                },

                message: 'This is a new message!',

                sendMail: []
            }

        }            

    }
</script>

<style>

</style>

// Angular/my-ninth-app/src/app/app.component.ts
import { Component, ViewChild } from '@angular/core';
import { NgForm } from '@angular/forms';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  
  @ViewChild('f') signupForm: NgForm;
  
  defaultQuestion: string = 'pet';
  answer: string = '';

  genders: string[] = ['male', 'female'];

  user = {
    username: '',
    email: '',
    secretQues: '',
    answer: '',
    gender: ''
  }

  submitted: boolean = false;

  suggestUserName(): void {
    
    const suggestedName = 'Superuser';

    // this.signupForm.setValue({
    //   userData: {
    //     username: 'suggestedName',
    //     email: ''
    //   },
    //   secret: 'pet',
    //   questionAnswer: '', 
    //   gender: 'male'
    // });

    this.signupForm.form.patchValue({
      userData: {
        username: suggestedName
      }
    });
  }

  // onSubmit(form: NgForm): void{
  //   console.log("Submitted-----");
  //   console.log(form);
  // }

  onSubmit(): void{
    // console.log(this.signupForm);

    this.submitted = true;

    this.user.username = this.signupForm.value.userData.username;
    this.user.email = this.signupForm.value.userData.email;
    this.user.secretQues = this.signupForm.value.secret;
    this.user.answer = this.signupForm.value.questionAnswer;
    this.user.gender = this.signupForm.value.gender;

    this.signupForm.reset();
  }

}

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-md-8 col-sm-offset-1 col-md-offset-2">
        <!-- Use @ViewChild('f') of onSubmit(f) -->
      <form (ngSubmit)="onSubmit()" #f="ngForm">
        <div id="user-data" 
          ngModelGroup="userData"
          #userData="ngModelGroup">
          <div class="form-group">
            <label for="username">Username</label>
            <input type="text" id="username" name="username" class="form-control" 
                  required ngModel>
          </div>
          
          <button class="btn btn-primary" type="button"
              (click)="suggestUserName()">Suggest an Username</button>
          
          <div class="form-group">
            <label for="email">Mail</label>
            <input type="email" id="email" name="email" class="form-control" 
                  required ngModel email #email="ngModel">
            <span class="help-block" *ngIf="!email.valid && email.touched">
                  Please enter a valid email!</span>
          </div>
        
        </div>

        <p *ngIf="!userData.valid && userData.touched">User Data is invalid!</p>

        <div class="form-group">
          <label for="secret">Secret Questions</label>
          <select id="secret" name="secret" class="form-control" 
              [ngModel]="defaultQuestion">
            <option value="pet">Your first Pet?</option>
            <option value="teacher">Your first teacher?</option>
          </select>
        </div>
        <div class="form-group">
          <textarea name="questionAnswer" rows="3" class="form-control"
                  [(ngModel)]="answer"></textarea>
        </div>
        <p>Your Reply: {{ answer }}</p>

        <div class='radio' *ngFor="let gender of genders">
          <label>
            <input type="radio" name="gender" 
                ngModel [value]="gender" required>
              {{gender}}
          </label>

        </div>

        <button class="btn btn-primary" type="submit"
                [disabled]="!f.valid">Submit</button>
      </form>
    </div>
  </div>

  <hr>

  <div class="row" *ngIf="submitted">
    <div class="col-xs-12">
      <h3>Your Data</h3>
      <P>Username: {{user.username}}</P>
      <p>Email: {{user.email}}</p>
      <p>Secret Question: Your First {{user.secretQues}}</p>
      <p>Answer: {{user.answer}}</p>
      <p>Gender: {{user.gender}}</p>
    </div>
  </div>

</div>
